# Generated by Django 3.0.5 on 2020-09-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_head', models.CharField(default='', max_length=50)),
                ('slider_desc', models.CharField(default='', max_length=200)),
                ('slider_img', models.ImageField(default='', upload_to='images/')),
            ],
        ),
    ]
