# Generated by Django 3.0.5 on 2020-09-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_auto_20200910_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderdata',
            name='slider_img',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
