# Generated by Django 3.0.5 on 2020-09-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_auto_20200910_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_head', models.CharField(default='', max_length=50)),
                ('card_desc', models.CharField(default='', max_length=200)),
                ('card_img', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
