# Generated by Django 3.0.5 on 2020-09-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0007_auto_20200910_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prod_height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='prod_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='prod_width',
            field=models.FloatField(default=0),
        ),
    ]
