# Generated by Django 3.0.5 on 2020-09-10 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0009_cooler_door_farmingtool_gate_grill_makhar_shutter_stair_tinshed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cooler',
        ),
        migrations.DeleteModel(
            name='Door',
        ),
        migrations.DeleteModel(
            name='FarmingTool',
        ),
        migrations.DeleteModel(
            name='Gate',
        ),
        migrations.DeleteModel(
            name='Grill',
        ),
        migrations.DeleteModel(
            name='Makhar',
        ),
        migrations.DeleteModel(
            name='Shutter',
        ),
        migrations.DeleteModel(
            name='Stair',
        ),
        migrations.DeleteModel(
            name='TinShed',
        ),
    ]
