# Generated by Django 3.0.5 on 2020-09-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0011_products_prod_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prod_cat',
            field=models.CharField(choices=[('gates_and_doors', 'Gates and Doors'), ('grills', 'Grills'), ('tin_sheds', 'Tin Sheds'), ('farming_tools', 'Farming Tools'), ('air_coolers', 'Air Coolers'), ('gauri_makhars', 'Gauri Makhars'), ('stairs', 'Stairs'), ('shutters', 'Shutters'), ('others', 'Others')], default='', max_length=30),
        ),
    ]
